version: "3"
services:
  space-warner-rust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: space-warner-rust
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
      - FILE_SYSTEMS=${FILE_SYSTEMS}
      - THRESHOLD=${THRESHOLD}
      - TRIGGER_INTERVAL=${TRIGGER_INTERVAL}
      - WARNING_INTERVAL=${WARNING_INTERVAL}
    working_dir: /root/app/
    volumes:
      - /home:/home  # make sure all volumes are added
